--- 
datadir: data/
debug: true
maxusers: 20
wateringsystem: 
  pump: 
    disable: true
    enable: false
    mode: out
    name: Pump
    pin: 18
  watersensor: 
    disable: true
    enable: false
    mode: out
    name: "Water Sensor"
    pin: 17
